[project]
name = "iota"
version = "0.1.0"
authors = ["Greg Chapple <gregchapple1@gmail.com>"]

[dependencies]
docopt = "0.6.40"
rustbox = "0.3.2"
rustc-serialize = "0.2.15"
gapbuffer = "0.1.0"

[lib]
name = "iota"
path = "src/iota/lib.rs"

[[bin]]
name = "iota"
doc = false
